steps:
  - name: 'bash'
    args: ['ls']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'update-covid-data-middleware-fn', '--trigger-topic=update-covid-data-middleware', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-md']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-br', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-br' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-cn', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-cn' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-it', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-it' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-mx', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-mx' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-pe', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-pe' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-sk', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-sk' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'update-covid-data-us', '--trigger-topic=update-covid-data', '--region=us-west1', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub', '--source=functions/update-covid-data-us' ]


options:
  logging: CLOUD_LOGGING_ONLY
