steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'update-covid-data-middleware-fn', 'update-fns', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub']
  - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'functions', 'deploy', 'update-covid-data-br', 'update-fns', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub' ]
  - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'functions', 'deploy', 'update-covid-data-us', 'update-fns', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub' ]
  - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'functions', 'deploy', 'update-covid-data-sk', 'update-fns', '--runtime', 'nodejs16', '--entry-point', 'helloPubSub' ]
